### ISSUE TITLE
Indexes implementation

### ISSUE THREAD

**Issue by Immortaal** [project-stocKING/stocking-server#13]
- interface for indexes
- one simply index to show that we can operate on data from database

**Comment by ParadoxBlack** [comment]
![index](https://cloud.githubusercontent.com/assets/17601616/13903894/36b1fa28-ee8d-11e5-9049-262a34316c24.png)

**Comment by ParadoxBlack** [comment]
Idea for implementation

**Comment by ParadoxBlack** [comment]
Test implemented indexes
