### ISSUE TITLE
Parsing data from frontend

### ISSUE THREAD

**Issue by cashis2903** [project-stocKING/stocking-server#18]

**Comment by ParadoxBlack** [comment]
Given the input received on port, we need to:
- Load data from database
- Calculate given indexes
- Generate Buy/Sell Signal
- Parse all calculated values to JSON

**Comment by ParadoxBlack** [comment]
Return indexes list to frontend

**Comment by ParadoxBlack** [comment]
Implemented returning indexes list to frontend as JSON via HTTP GET Request. Implementation is temporary in future it will be better to create database for indexes
