### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by ParadoxBlack** [project-stocKING/stocking-server#3]
Write a program which:
- Will read given file and prepare data
- Will insert prepared data into database
- Will check if data is not already in database

Preferred language - Java, but it's not necessary. It will be probably independent from main java program.

**Comment by cashis2903** [comment]
This program should iterate by files or user would choose file (like argument?) and parser will do the tricks with it ? 
I'm connected with db and now i'm trying to learn how to use mongo api :+1:

**Comment by cashis2903** [comment]
This is small diffrences beetwen normal database like mysql and mongo

RDBMS   MongoDB
Database    Database
Table   Collection
Tuple/Row   Document
column  Field
Table Join  Embedded Documents
Primary Key Primary Key (Default key _id provided by mongodb itself)

**Comment by ParadoxBlack** [comment]
Parser is almost done. Insert data into database when the server connection problem will be solved.
