### ISSUE TITLE
ERD diagrams

### ISSUE THREAD

**Issue by Immortaal** [project-stocKING/stocking-server#5]
ERD diagrams for database. (The first will be represent stock's tables, the second - client's tables). We will use end of day data so that's why database has this structure. Only 8 the most popular stock for tests.

**Comment by Immortaal** [comment]
![diagramerd_stock](https://cloud.githubusercontent.com/assets/17602230/13677762/a361f820-e6eb-11e5-9a0d-db8c6c4fb2b4.png)

**Comment by Immortaal** [comment]
Only 8 the most popular stock for tests

**Comment by Immortaal** [comment]
![clientdiagramerd](https://cloud.githubusercontent.com/assets/17602230/13688084/bc6806f0-e71f-11e5-9189-99dea33f9aeb.png)

**Comment by ParadoxBlack** [comment]
Users should have userID instead of idUsers, it will look better :)

**Comment by Immortaal** [comment]
It's auto-generated by MySQL Workbench, you can see that in all tables is used this convention. I can correct it, no problem, but I'm still waiting for Olek

**Comment by cashis2903** [comment]
So I have some problems with diagrams. First, there is typo in PZWBK, there should be BZWBK :). Second, volume cannot be in Integer becouse sometimes Java generate error with integer on float or double there is no problem.

**Comment by Immortaal** [comment]
Ok, I will correct it.

**Comment by Immortaal** [comment]
![stock](https://cloud.githubusercontent.com/assets/17602230/13732086/7b5c5406-e97a-11e5-83f2-a148a210c251.png)

**Comment by Immortaal** [comment]
![users](https://cloud.githubusercontent.com/assets/17602230/13732129/77899db0-e97b-11e5-9e82-e7fd7299156b.png)
