### ISSUE TITLE
Create clients' tables using Hibernate

### ISSUE THREAD

**Issue by Immortaal** [project-stocKING/stocking-server#6]
The second database will be relational so we can create a client's tables using Hibernate

**Comment by Immortaal** [comment]
I set up a local MySQL database and I created User and Authorization tables using Hibernate. I have to test basic operations like insert, delete or update.

**Comment by ajaskier** [comment]
Client database is a part of web app, written in Rails, which creates and manages database by itself, so there's no need for you to create it.
