### ISSUE TITLE
Getting data from database

### ISSUE THREAD

**Issue by ParadoxBlack** [project-stocKING/stocking-server#9]
First part of server application. Write a simple program which will load collection from database. Collection will be chosen by stock company name.

**Comment by Immortaal** [comment]
Now we can load a collection from database by stock company name and this collection is converted to array list of stock companies objects

**Comment by ParadoxBlack** [comment]
TODO:
- Implement this as it is shown in class diagram: Server connection: abstract class which only maintains database connection, then create class for endOfDayDB. Find docs by date should return ArrayList of StockCompanies
